[package]
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"
name = "xcm-builder"
description = "Tools & types for building with XCM and its executor."
version = "0.9.9"

[dependencies]
parity-scale-codec = { version = "2.0.0", default-features = false, features = ["derive"] }
xcm = { path = "..", default-features = false }
xcm-executor = { path = "../xcm-executor", default-features = false }
sp-std = { git = "https://github.com/paritytech/substrate", default-features = false , branch = "bkchr-update-wasmtime-0.29.0" }
sp-arithmetic = { git = "https://github.com/paritytech/substrate", default-features = false , branch = "bkchr-update-wasmtime-0.29.0" }
sp-io = { git = "https://github.com/paritytech/substrate", default-features = false , branch = "bkchr-update-wasmtime-0.29.0" }
sp-runtime = { git = "https://github.com/paritytech/substrate", default-features = false , branch = "bkchr-update-wasmtime-0.29.0" }
frame-support = { git = "https://github.com/paritytech/substrate", default-features = false , branch = "bkchr-update-wasmtime-0.29.0" }
frame-system = { git = "https://github.com/paritytech/substrate", default-features = false , branch = "bkchr-update-wasmtime-0.29.0" }
pallet-transaction-payment = { git = "https://github.com/paritytech/substrate", default-features = false , branch = "bkchr-update-wasmtime-0.29.0" }
log = { version = "0.4.0", default-features = false }

# Polkadot dependencies
polkadot-parachain = { path = "../../parachain", default-features = false }

[dev-dependencies]
sp-core = { git = "https://github.com/paritytech/substrate", branch = "bkchr-update-wasmtime-0.29.0" }
pallet-balances = { git = "https://github.com/paritytech/substrate", branch = "bkchr-update-wasmtime-0.29.0" }
pallet-xcm = { path = "../pallet-xcm" }
polkadot-runtime-parachains = { path = "../../runtime/parachains" }
[features]
default = ["std"]
runtime-benchmarks = []
std = [
	"log/std",
	"parity-scale-codec/std",
	"xcm/std",
	"xcm-executor/std",
	"sp-std/std",
	"sp-arithmetic/std",
	"sp-io/std",
	"sp-runtime/std",
	"frame-support/std",
	"polkadot-parachain/std",
	"pallet-transaction-payment/std",
]
